
Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'test/**/*'
    - 'vendor/**/*'

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
